<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Memoline.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Hashing">
      <HintPath>..\..\Recognizer\publish\win-x64\System.IO.Hashing.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
